### ISSUE TITLE
Image Thumbnails not showing & Not able to connect to uploaded gallery

### ISSUE THREAD

**Issue by eiertee** [ainterpreting/mosaico-php-backend#1]
Hello there!

First of all a HUGE big up for your amazing work! I am trying to setup a mosaic editor using your php backend and have been able to do so up to the said issues. I mainly find myself getting the  /img/?method=placeholder&params=534%2C200 error over and over again... Have everything setup as it should, imagick php extension up and running but still no luck --> thumbnails are shown as 'broken' even though i see in the browser console that everything is pointing correctly. & in the editor itself, i can't access the uploaded files gallery, even though i see that they are effectively uploaded to the server.... Any thoughts?

**Comment by mherbold** [comment]
Check the paths you have set up in Mosaico.  In the sample editor.html file I had to make some changes to this file (remove leading slashes from paths) get my Mosaico installation working in a subfolder.  Perhaps you are running into the same issue?
