### ISSUE TITLE
Cannot upload pictures on WAMP

### ISSUE THREAD

**Issue by parismav87** [ainterpreting/mosaico-php-backend#5]
Hello, and congratulations on your great project!
I have a problem: 
I have transferred all the necessary files (with the apache backend sample) to my wamp/www folder, and when i enter localhost:9000 I can see the template selector screen. I can also create a template, block by block, but when trying to upload images, it fails. I can't see the image in the "recents" tab, although a copy of the image is created in "uploads" folder in the file system. 
Grunt is running with no errors. 
Any help would be appreciated

**Comment by bwl21** [comment]
You need to check if ImageMagick works properly. Maybe you have to enable the php extesion.

In your php.ini, you should have:

``` php
extension=imagick.so
```
